### PR TITLE
Renamed files and added 5 problems

### PR DESCRIPTION
**Pull request by zahyaah**
### Added following Leetcode solutions
Issue #78 
1) 1351 Count Negative Numbers in a Sorted Matrix
image

2) 1572 Matrix Diagonal Sum
image

3) 231 Power of Two
image

4) 43 Multiply Strings
image

5) 1346 Check If N and Its Double Exist
image

### Renamed the files and attached links inside them.

### CODE REVIEW

**Comment by Adarsh-jaiss** [comment]
- Looks good to me 😄

**Review by Adarsh-jaiss — APPROVED** [review]

**Comment by zahyaah** [comment]
Thank you @Adarsh-jaiss It's my first Hacktoberfest contribution :)

**Comment by Adarsh-jaiss** [comment]
- Please change the directory and create the new PR, I need to revert it  because you have added it in main directory other than adding it to the folder

**Comment by zahyaah** [comment]
So, I need to create a new branch and submit it to some other branch of codemistic/Data-Structures-and-Algorithms rather than main, right? @Adarsh-jaiss

**Pull request merged**
