### PR TITLE
added a new dp problem and working solution. Please review it and merge it

### PR DESCRIPTION
**Pull request by Eswari-Priya**

### CODE REVIEW

**Comment by Eswari-Priya** [comment]
Hello @gantavyamalviya , May I know why this submission is invalid? Please let me know, so I could make required changes and make a new PR.
Thank you

**Comment by gantavyamalviya** [comment]
@Eswari-Priya You file in empty, pls check on your end.

**Comment by Eswari-Priya** [comment]
Ok, I'm extremely sorry about that, I just added the working code. Please review it and merge it. Thank you @gantavyamalviya

**Comment by gantavyamalviya** [comment]
@Eswari-Priya Thanks for your contribution

**Pull request merged**
